### ISSUE TITLE
Question on how to update resource managers during runtime

### ISSUE THREAD

**Issue by cMurschall** [Jinjinov/wpf-localization-multiple-resource-resx-one-language#1]
Hi, 
thanks for the great idea, it works so well, but I don't understand how to change language during runtime. My hope was to do it on the selection changed event of a combox like:
```c#
private void Selector_OnSelectionChanged(object sender, SelectionChangedEventArgs e)
{
    var content = ((ComboBoxItem)e.AddedItems[0]).Content.ToString();
    switch (content)
    {
        case "en":
            Translation.SetResourceManager(this, Properties.ResourcesEn.ResourceManager);
            break;
        case "de":
            Translation.SetResourceManager(this, Properties.ResourcesDe.ResourceManager);
            break;
    }
}
```
but the language is not updated. I did also try to change the `CurrentCulture` like:
```c#
TranslationSource.Instance.CurrentCulture = new CultureInfo("en-US");
```
and hoped it would reevaluate all bindings, but this also does not update the bindings. 

Perhaps you could point me into the right direction. Thank you!

**Comment by Jinjinov** [comment]
You should never call `Translation.SetResourceManager` from code (because you set the resource manager in xaml) and you should always have a single resource manager in one project for all languages. Multiple resource managers are still one per project (for all languages) so `ResourcesEn` and `ResourcesDe` is wrong.

My advice would be that you read Jakub's original post very carefully and that you follow my Readme very carefully. Based on your code it seems like you misunderstood the purpose of a `DependencyObject` - perhaps read a tutorial about dependency objects.
